apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous false
    password_file /mosquitto/config/password.txt

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
data:
  password.txt: |
    mqtt:$7$100$8r1GiyG1+bWi3yta$J8jtiy0c8jy/WMpPuOQRI4X2ZknZyz23grpP4M60jbivWlj/gFR37Z4fNv+sn0NGcCeigwMEJ/r4ROq5v/JSbA==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - image: eclipse-mosquitto:2.0.22
        name: mosquitto
        ports:
        - containerPort: 1883
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: mosquitto-pvc
          mountPath: /mosquitto/data
        - name: mosquitto-password
          mountPath: /mosquitto/config/password.txt
          subPath: password.txt
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mosquitto-pvc
        persistentVolumeClaim:
          claimName: mosquitto-pvc
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
      - name: mosquitto-config
        configMap:
          name: mosquitto-config

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-nodeport
  labels:
    app: mosquitto
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 30083
